name: Fast Video Downloader

on:
  workflow_dispatch:
    inputs:
      quality:
        description: "Video Quality"
        required: true
        default: "720"
        type: choice
        options:
          - "360"
          - "480"
          - "720"
          - "1080"

      links:
        description: "Paste video links"
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y aria2 ffmpeg
          python3 -m pip install -U yt-dlp

      - name: Prepare folders
        run: |
          mkdir -p downloads
          mkdir -p logs

      - name: Write cookies
        run: |
          cat > cookies.txt << 'EOF'
          ${{ secrets.PH_COOKIE }}
          EOF

      - name: Extract links
        env:
          LINKS: ${{ github.event.inputs.links }}
        run: |
          echo "$LINKS" | tr ' ' '\n' | sed '/^$/d' > parsed_links.txt

          echo "====== LINKS ======"
          cat parsed_links.txt

      - name: Download videos
        env:
          QUALITY: ${{ github.event.inputs.quality }}
        run: |
          touch logs/success.txt
          touch logs/failed.txt

          while read url; do

            echo "=============================="
            echo "Downloading: $url"
            echo "=============================="

            yt-dlp \
              --cookies cookies.txt \
              --extractor-args "pornhub:client=web" \
              --add-header "Referer:https://www.pornhub.com/" \
              --add-header "Origin:https://www.pornhub.com" \
              --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36" \
              --retries 20 \
              --fragment-retries 20 \
              --retry-sleep 5 \
              --concurrent-fragments 8 \
              --file-access-retries 10 \
              --socket-timeout 30 \
              --no-check-certificates \
              --geo-bypass \
              --geo-bypass-country US \
              -f "best[height<=${QUALITY}]" \
              --merge-output-format mp4 \
              --downloader aria2c \
              --downloader-args "aria2c:-x 16 -s 16 -k 1M --file-allocation=none" \
              -o "downloads/%(title).120s.%(ext)s" \
              "$url"

            if [ $? -eq 0 ]; then
              echo "$url" >> logs/success.txt
              echo "SUCCESS"
            else
              echo "$url" >> logs/failed.txt
              echo "FAILED"
            fi

          done < parsed_links.txt

      - name: Show results
        run: |
          echo ""
          echo "========== SUCCESS =========="
          cat logs/success.txt || true

          echo ""
          echo "========== FAILED =========="
          cat logs/failed.txt || true

      - name: Upload Downloads
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-videos
          path: downloads/
          if-no-files-found: ignore

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
