name: Fast Video Downloader

on:
  workflow_dispatch:
    inputs:
      quality:
        description: "Video Quality"
        required: true
        default: "720"
        type: choice
        options:
          - "360"
          - "480"
          - "720"
          - "1080"

      links:
        description: "Paste video links"
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y aria2 ffmpeg
          python3 -m pip install -U yt-dlp

      - name: Prepare folders
        run: |
          mkdir -p downloads
          mkdir -p logs

      - name: Write cookies
        run: |
          echo "${{ secrets.PH_COOKIE }}" > cookies.txt

      - name: Extract links
        env:
          LINKS: ${{ github.event.inputs.links }}
        run: |
          echo "$LINKS" | tr ' ' '\n' | sed '/^$/d' > parsed_links.txt
          echo "====== LINKS ======"
          cat parsed_links.txt

      - name: Download videos
        env:
          QUALITY: ${{ github.event.inputs.quality }}
        run: |
          touch logs/success.txt
          touch logs/failed.txt

          while read url; do
            echo "=============================="
            echo "Downloading: $url"
            echo "=============================="

            yt-dlp \
              --cookies cookies.txt \
              --add-header "User-Agent: Mozilla/5.0" \
              --extractor-args "pornhub:client=web" \
              --retries 10 \
              --fragment-retries 10 \
              --concurrent-fragments 8 \
              --file-access-retries 10 \
              --retry-sleep 5 \
              -f "bestvideo[height<=${QUALITY}]+bestaudio/best[height<=${QUALITY}]" \
              --merge-output-format mp4 \
              --downloader aria2c \
              --downloader-args "aria2c:-x 16 -s 16 -k 1M" \
              -o "downloads/%(title)s.%(ext)s" \
              "$url"

            if [ $? -eq 0 ]; then
              echo "$url" >> logs/success.txt
              echo "SUCCESS"
            else
              echo "$url" >> logs/failed.txt
              echo "FAILED"
            fi

          done < parsed_links.txt

      - name: Show results
        run: |
          echo ""
          echo "========== SUCCESS =========="
          cat logs/success.txt || true

          echo ""
          echo "========== FAILED =========="
          cat logs/failed.txt || true

      - name: Upload Downloads
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-videos
          path: downloads/

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
